Repository monstertrux/environment-cloudsmart-cluster1-dev, pull requests merged in 2020-12, with the labels that each got.

#4 chore(deps): bump https://github.com/monstertrux/google-pubsub-emulat…
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/monstertrux-google-pubsub-emulator-sr.yaml
Labels: size/S

#5 feat(config): upgrade configuration
  bdd/bdd.sh
  bdd/boot-local/jx-requirements.yml
  bdd/boot-vault/jx-requirements.yml
  env/Makefile
  env/jenkins-x-platform/values.tmpl.yaml
  env/jxboot-resources/values.tmpl.yaml
  env/lighthouse-jx/README.MD
  env/lighthouse-jx/values.tmpl.yaml
  env/lighthouse/values.tmpl.yaml
  env/parameters.tmpl.schema.json
  env/requirements.yaml
  env/tekton/values.tmpl.yaml
  env/values.tmpl.yaml
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
  jenkins-x.yml
  jx-requirements.yml
  kubeProviders/aks/values.tmpl.yaml
  kubeProviders/eks/values.tmpl.yaml
  kubeProviders/gke/values.tmpl.yaml
  kubeProviders/iks/README.md
  kubeProviders/iks/iks-app.png
  kubeProviders/iks/values.tmpl.yaml
  kubeProviders/kubernetes/values.tmpl.yaml
  kubeProviders/openshift/templates/README.md
  kubeProviders/openshift/templates/controller-build-scc.yaml
  kubeProviders/openshift/templates/jx-admin-role.yaml
  kubeProviders/openshift/templates/namespaces.yaml
  kubeProviders/openshift/templates/service-accounts.yaml
  kubeProviders/openshift/templates/tekton-crds.yaml
  systems/acme/Chart.yaml
  systems/external-dns/values.tmpl.yaml
  systems/jxing/requirements.yaml
  systems/jxing/values.tmpl.yaml
  systems/velero-backups/README.MD
  systems/velero/README.MD
  systems/velero/requirements.yaml
  systems/velero/values.tmpl.yaml
Labels: approved, size/XXL

#6 Update jx-requirements
  jx-requirements.yml
  systems/acme/Chart.yaml
Labels: size/XS

#7 feat(config): upgrade configuration
  env/Makefile
  jx-requirements.yml
Labels: approved, size/XS

#8 [PR] Add missing repo
  env/Makefile
Labels: size/XS

#9 [PR] Add helm init on build
  env/Makefile
Labels: size/XS
